### PR TITLE
CGP-695: Stripe payment tests

### PR DESCRIPTION
**Pull request by coldrunKacper**
tests/phpunit/CiviTest/CiviSeleniumSettings.php

$sandboxURL
$username
$password
$adminUsername
$adminPassword

The changes include Selenium web test to test both Drupal webform and CiviCRM Contribute page payments. There is also webform node code included and used by test script to automatically install test webform. The test webform is deleted after webform test is completed.
Both test methods create printscreens on completing the test.

**Steps to configure the tests depending on particular site instance:**

1. Edit tests/phpunit/CiviTest/CiviSeleniumSettings.php with proper values of:
- $sandboxURL
- $username (drupal username, can be the same as drupal admin user)
- $password (drupal password, can be the same as drupal admin password)
- $adminUsername (drupal admin username)
- $adminPassword (drupal admin password)

2. Set tests/printscreen directory permissions to writable.

**Running the tests:**

First, Selenium server is needed to be up and running. The branch includes selenium.jar file which can be used to run the server.
It can be run by executing:

`DISPLAY=:1 xvfb-run -a java -jar selenium.jar`

while being in bin/selenium directory.

To run the web tests please execute:

`phpunit`

from command line while being in com.drastikbydesign.stripe directory.

The complete test takes up to 2 minutes to finish. I didn't optimize it yet but I'll try to use Headless Interface. Anyway some operations have to take some time as the test runs on "live" browser instance and requires some time to refresh particular page, reload ajax callbacks, etc.

### CODE REVIEW

**Comment by AkA84** [comment]
@coldrunKacper some comments:

1. Why did you need to push the `Civi/Test/` files? Aren't they supposed to be included by default in every CiviCRM build?
2. What's the need for Selenium Server at all? I'm not aware that we're using in the other (few) tests that we currently have for example in CiviHR. According to the [documentation](http://docs.seleniumhq.org/docs/03_webdriver.jsp):
> There are some reasons though to use the Selenium-Server with Selenium-WebDriver.
> You are using Selenium-Grid to distribute your tests over multiple machines or virtual machines (VMs).
> You want to connect to a remote machine that has a particular browser version that is not on your current machine.
> You are not using the Java bindings (i.e. Python, C#, or Ruby) and would like to use HtmlUnit Driver
3. You have custom (i assume they are custom at least) files like `AuthorizeNet.php` `Membership.php`, `Event.php` in the `CiviTest/` folder alongside other files that instead seem to be more about the overall test infrastructure (`civicrm.settings.local.php`, `bootstrap.php`, `CiviSeleniumTestCase.php`, etc). What are those? Helpers? Page objects? Shouldn't they placed somewhere else? 
4. What are you using the screenshots for?

**Comment by coldrunKacper** [comment]
Thanks @AkA84 
1. Yes, Civi and tests/phpunit/CiviTest directories are supposed to be included by default CiviCRM build - but, for example, CEW site doesn't have them (for unknown reason) so I decided to include their copy into the extension to keep everything independent of particular site setup.
2. I need to talk with Davi about it (probably tomorrow, as Davi is away today).
3. Right, these files came with whole CiviTest directory copy. I've removed most of them in my latest commit and left only few which are required to run the test.
4. I was using screenshots to check final "browser" result after each test but I can remove screenshots as they add another complication to the setup (require to set write permissions to screenshot directory).

**Comment by AkA84** [comment]
@coldrunKacper about point no.4: what is this "check" that would do on screenshots? Was it just you checking "manually" that the page looked right? The screenshots seem they have nothing to do with the tests themselves, so unless you were using them for some visual diffing, i'm not sure what the benefits of having them would be

**Comment by AkA84** [comment]
@coldrunKacper also, about `CiviCRMSeleniumSettings.php`: is this file auto-generated somehow? Or did you copy it from somewhere? If it's auto-generated then I guess there is no need to include it in the repo. If instead you had to copy-paste it, then at least I'd say maybe it would be better to have placeholders in places for the primary variables instead of your local settings, something like:
```php
// Replace placeholders values with your local site settings
var $sandboxURL = 'http://%{local_site_host}';
var $username = '%{regular_user_name}';
var $password = '%{regular_user_password}';
var $adminUsername = '%{admin_user_name}';
var $adminPassword = '%{admin_user_pwd}';
```
what do you think?

**Comment by davialexandre** [comment]
@coldrunKacper the files under tests/phpunit/CiviTest are not required. Here's what needs to be done:
- Change this line in [bootstrap.php](https://github.com/compucorp/com.drastikbydesign.stripe/blob/CGP-695-stripe-payment-tests/tests/phpunit/bootstrap.php#L5) to `eval(cv('php:boot --level=full -t', 'phpcode'));` (this will make sure all the required classes and enviroment variables for e2e tests will be available during tests)
- Remove the require_once from the test class
- Implement the Headless interface and use the setupHeadless method to install the extension (check L&A tests for reference https://github.com/civicrm/civihr/blob/la-milestone-3/uk.co.compucorp.civicrm.hrleaveandabsences/tests/phpunit/WebTest/AbsencePeriod/FormTest.php)
- Make sure you have everything set on the ~/.cv.json file (check this for more details https://compucorp.atlassian.net/wiki/display/PCHR/Tests+in+CiviCRM+v4.7)
- Edit the civicrm/tests/phpunit/CiviTest/CiviSeleniumSettings.auto.php file if you need. You will need to add rcHost and rcPort properties if you're not running selenium with the default port or in a different machine than the one where you're running the tests (for example, when you use Vagrant and run the tests on the guest VM but have selenium-server running in the host)

With all that, you should be able to run the tests with `phpunit4` (not `phpunit`, as mentioned on the ticket description). 

Besides this, I have a few more points:

- I'm not sure if you really need the drupal bootstrap piece of code on the test. Can you give more details about what doesn't work if you remove it? If you really need it, then it would be better to put it in the bootstrap.php file
- selenium-server.jar should definitely not be added to the repository. It should be installed as part of the 'local dev setup'. If the set up for some sites does not include it, then it should be updated.
- We still have a lot of things to decide regarding e2e tests. One of them is directory structure, including where to put helpers or fixtures. In the test context, the `tests/webform/payment_webform.node` file is a fixture, so I think it would probably be better move it to a directory like` tests/fixtures/webform/`. As least until we figure out a better directory structure to tests

**Comment by coldrunKacper** [comment]
@Davi thanks for the advices, I'm implementing them into the test. Anyway, as I run the test on my local CEW project - not all seems to work with your solution - for example CEW doesn't have civicrm/Civi/Test directory (or even civicrm/tests) so that's why I thought that include them into the test files would be a good idea. What do you think? Or should we update the project with missing civicrm files?

**Comment by coldrunKacper** [comment]
@davi here's the CEW civicrm directory: https://bitbucket.org/compucorp/cew/src/f9da5c3cdb922b6778a20605b4331ffb9c4f699f/sites/all/modules/civicrm/?at=master

**Comment by jamienovick** [comment]
Hey guys,

Couple of things.

1. Normal client sites do not have tests installed. They are built from tarball from sourceforge. 

2. In terms of this extension however the tests should not be designed with a client in mind. The tests should be against a clean civicrm install.

3. As such the test structure should assume that it is being tested within a civitesting environment i.e. one built by buildkit and should be using its dependencies.

Ideally the vision is that we can test this against any latest or specific civicrm version in buildkit.

In terms of webform. If there are dependencies we add those as part of the entire test stack so when the test runs it gets the latest webform and installs it etc and creates a sample webform configured for payment.

Does that sound doable?

The next step then is about putting this all somewhere where the tests can be run. Now given we havent got jenkins up yet my thinking is that we may be able to get this as part of core jenkins test stack as it is a widely used extension.

Ill ping tim/eileen/coleman and see whatbthe story is.

**Pull request closed without merging**
